CREATE TABLE items
(id BIGINT AUTO_INCREMENT PRIMARY KEY ,
 item_code VARCHAR(20)UNIQUE NOT NULL,
 name VARCHAR(20) NOT NULL,
 price INT NOT NULL,
 init_price INT NOT NULL
);

CREATE TABLE users
(id BIGINT AUTO_INCREMENT PRIMARY KEY ,
 login VARCHAR(20)UNIQUE NOT NULL,
 password VARCHAR(20)UNIQUE NOT NULL,
 first_name VARCHAR(20)NOT NULL,
 last_name VARCHAR(20),
 email VARCHAR(50)NOT NULL,
 phone VARCHAR(20)NOT NULL
);

CREATE TABLE orders
(id BIGINT AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT NOT NULL ,
 creation_time BIGINT NOT NULL ,
 status VARCHAR(10)NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE order_items
(id BIGINT AUTO_INCREMENT PRIMARY KEY,
 item_id BIGINT NOT NULL,
 order_id BIGINT NOT NULL,
 amount INT NOT NULL,
 FOREIGN KEY (item_id) REFERENCES items (id),
 FOREIGN KEY (order_id) REFERENCES orders (id)
);
